language: php
php:
  - 5.5
  - 5.6
  - 7.1
  - 7.2
  - 7.3
install: composer install --dev
before_script:
  - git config --global user.email "dev.pmill@gmail.com"
  - git config --global user.name "pmill"

after_script:
  - php vendor/bin/test-reporter
